### ISSUE TITLE
dependency problem, haba module

### ISSUE THREAD

**Issue by sajadbahar** [crcn/beanpoll.js#98]
you use haba module as dependency but but this module not exist any more, please review dependency and code

**Comment by crcn** [comment]
beanpoll hasn't been maintained in a while. The concepts are solid, but I've been working on other stuff. checkout [crema](https://github.com/crcn/crema.js), and [dolce](https://github.com/crcn/dolce.js) if you like how routing is done.

**Comment by crcn** [comment]
Fixed.
